name: chat_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  flutter:
    sdk: flutter
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.2
  uuid: ^3.0.4

  cupertino_icons: ^1.0.2
  file_picker: ^4.5.1
  permission_handler: ^9.2.0
  path_provider: ^2.0.9
  open_file: ^3.2.1
  animated_text_kit: ^4.2.1
  selectable_autolink_text: ^2.3.0
  url_launcher: ^6.1.4
  flutter_native_splash: ^2.2.3+1
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png